// 全銘柄マスタ。puzzles.js と fetch-data.mjs の共通ソース。
// 追加する場合はこの配列に1行足して node scripts/build-puzzles.mjs を実行。

export const STOCKS = [
  { answer: "任天堂", aliases: ["nintendo", "にんてんどう"], ticker: "7974.T", code: "7974", sector: "情報・通信／ゲーム", mcap: "約10兆円", keyword: "京都本社・世界的キャラクターIP", kana: "に", desc: "京都発のゲーム最大手。ハードの世代交代とIP展開が株価の主材料です。" },
  { answer: "東京電力ホールディングス", aliases: ["東電", "東京電力", "tepco"], ticker: "9501.T", code: "9501", sector: "電気・ガス", mcap: "約1兆円", keyword: "首都圏インフラ・原発再稼働", kana: "と", desc: "首都圏の電力インフラを担う。原発再稼働や電力需給のニュースで大きく動きます。" },
  { answer: "ファーストリテイリング", aliases: ["ユニクロ", "uniqlo"], ticker: "9983.T", code: "9983", sector: "小売（アパレル）", mcap: "約13兆円", keyword: "日経寄与度最大級・海外売上", kana: "ふ", desc: "ユニクロを世界展開するアパレル最大手。日経平均への寄与度が大きい銘柄です。" },
  { answer: "楽天グループ", aliases: ["楽天", "rakuten"], ticker: "4755.T", code: "4755", sector: "情報・通信／EC", mcap: "約2兆円", keyword: "モバイル巨額投資・ポイント経済圏", kana: "ら", desc: "ECとポイント経済圏を軸にモバイルへ投資。携帯事業の損益が最大の焦点です。" },
  { answer: "三菱重工業", aliases: ["三菱重工", "mhi"], ticker: "7011.T", code: "7011", sector: "機械／重工", mcap: "約7兆円", keyword: "防衛・ガスタービン・宇宙", kana: "み", desc: "防衛・エネルギー・宇宙を担う重工の雄。防衛費増額の流れを強く受けます。" },
  { answer: "トヨタ自動車", aliases: ["トヨタ", "toyota"], ticker: "7203.T", code: "7203", sector: "自動車", mcap: "約45兆円・日本最大", keyword: "ハイブリッド王者・世界販売トップ", kana: "と", desc: "時価総額日本一の自動車メーカー。為替と北米販売が株価を左右します。" },
  { answer: "ソニーグループ", aliases: ["ソニー", "sony"], ticker: "6758.T", code: "6758", sector: "電気機器／エンタメ", mcap: "約20兆円", keyword: "ゲーム・音楽・映画・センサー", kana: "そ", desc: "ゲーム・音楽・映画・半導体を束ねる複合企業。エンタメの稼ぐ力が評価の中心です。" },
  { answer: "キーエンス", aliases: ["keyence"], ticker: "6861.T", code: "6861", sector: "FA・計測機器", mcap: "約15兆円", keyword: "営業利益率50%超・大阪本社", kana: "き", desc: "FAセンサーで超高収益。世界の設備投資サイクルに敏感な銘柄です。" },
  { answer: "東京エレクトロン", aliases: ["東エレク", "tel"], ticker: "8035.T", code: "8035", sector: "半導体製造装置", mcap: "約12兆円", keyword: "半導体装置世界大手・AI投資", kana: "と", desc: "半導体製造装置の世界大手。AI向け投資の強弱がそのまま株価に出ます。" },
  { answer: "三菱UFJフィナンシャル・グループ", aliases: ["三菱UFJ", "mufg"], ticker: "8306.T", code: "8306", sector: "銀行", mcap: "約25兆円・邦銀最大", keyword: "金利上昇最大受益者・メガバンク", kana: "み", desc: "国内最大の金融グループ。日銀の利上げ観測が最大の変動要因です。" },
  { answer: "日立製作所", aliases: ["日立", "hitachi"], ticker: "6501.T", code: "6501", sector: "総合電機", mcap: "約20兆円", keyword: "Lumada・送配電・事業再編", kana: "ひ", desc: "ITと社会インフラに集中した総合電機。事業再編で評価が一変しました。" },
  { answer: "NTT", aliases: ["日本電信電話", "ntt"], ticker: "9432.T", code: "9432", sector: "情報・通信", mcap: "約13兆円", keyword: "25分割・元国営・IOWN", kana: "え", desc: "元国営の通信最大手。株式分割で個人株主が急増したことでも話題に。" },
  { answer: "KDDI", aliases: ["au", "kddi"], ticker: "9433.T", code: "9433", sector: "情報・通信", mcap: "約11兆円", keyword: "au・20期超連続増配", kana: "け", desc: "auを展開する通信大手。20期超の連続増配で配当株として人気です。" },
  { answer: "オリエンタルランド", aliases: ["OLC", "ディズニー"], ticker: "4661.T", code: "4661", sector: "レジャー", mcap: "約6兆円", keyword: "舞浜テーマパーク・値上げ戦略", kana: "お", desc: "舞浜のテーマパーク運営。入園者数と客単価のバランスが常に注目されます。" },
  { answer: "第一三共", aliases: ["daiichi sankyo"], ticker: "4568.T", code: "4568", sector: "医薬品", mcap: "約7兆円", keyword: "ADC抗体薬物複合体・がん治療", kana: "だ", desc: "がん治療薬ADCで世界をリード。治験結果が株価の最大材料です。" },
  { answer: "資生堂", aliases: ["shiseido"], ticker: "4911.T", code: "4911", sector: "化粧品", mcap: "約1兆円", keyword: "中国市場・銀座発祥", kana: "し", desc: "銀座発祥の化粧品最大手。中国・インバウンド消費が業績を左右します。" },
  { answer: "日産自動車", aliases: ["日産", "nissan"], ticker: "7201.T", code: "7201", sector: "自動車", mcap: "約1兆円", keyword: "経営再建・統合協議", kana: "に", desc: "経営再建中の自動車大手。提携・統合をめぐる報道が材料になります。" },
  { answer: "ホンダ", aliases: ["本田", "honda"], ticker: "7267.T", code: "7267", sector: "自動車・二輪", mcap: "約8兆円", keyword: "二輪世界首位・EV戦略", kana: "ほ", desc: "二輪世界首位。EV戦略と大規模自社株買いが話題の銘柄です。" },
  { answer: "メルカリ", aliases: ["mercari"], ticker: "4385.T", code: "4385", sector: "フリマアプリ", mcap: "約4000億円", keyword: "フリマ最大手・メルペイ", kana: "め", desc: "フリマアプリ最大手。米国事業とフィンテックが評価の焦点です。" },
  { answer: "サイバーエージェント", aliases: ["cyberagent", "CA"], ticker: "4751.T", code: "4751", sector: "ネット広告・ゲーム", mcap: "約6000億円", keyword: "ABEMA・スマホゲーム", kana: "さ", desc: "ネット広告・ゲーム・ABEMAの3本柱。ゲームヒットで業績が大きく振れます。" },
  { answer: "ZOZO", aliases: ["ゾゾタウン", "zozotown"], ticker: "3092.T", code: "3092", sector: "ファッションEC", mcap: "約1.5兆円", keyword: "ファッションEC最大手・高利益率", kana: "ぞ", desc: "ファッションEC最大手。取扱高の伸びと高い利益率が評価のポイントです。" },
  { answer: "JR東海", aliases: ["東海旅客鉄道", "リニア"], ticker: "9022.T", code: "9022", sector: "鉄道", mcap: "約4兆円", keyword: "東海道新幹線・リニア建設", kana: "じ", desc: "東海道新幹線のドル箱。リニア中央新幹線の投資行方が長期の焦点です。" },
  { answer: "ANAホールディングス", aliases: ["ANA", "全日空"], ticker: "9202.T", code: "9202", sector: "空運", mcap: "約1.5兆円", keyword: "国内線首位・インバウンド回復", kana: "え", desc: "国内線シェア首位級。インバウンド需要と燃油価格が業績のカギです。" },
  { answer: "日本製鉄", aliases: ["日鉄", "nippon steel"], ticker: "5401.T", code: "5401", sector: "鉄鋼", mcap: "約3.5兆円", keyword: "粗鋼国内首位・米鉄鋼買収", kana: "に", desc: "粗鋼生産国内首位。米大手鉄鋼メーカー買収が注目されています。" },
  { answer: "ENEOSホールディングス", aliases: ["エネオス", "eneos"], ticker: "5020.T", code: "5020", sector: "石油", mcap: "約2.5兆円", keyword: "GS最大手・原油連動", kana: "え", desc: "ガソリンスタンド網国内最大。原油価格と株主還元が主材料です。" },
  { answer: "花王", aliases: ["kao"], ticker: "4452.T", code: "4452", sector: "日用品", mcap: "約3兆円", keyword: "30期超連続増配・アタック", kana: "か", desc: "アタックやビオレを擁する日用品大手。国内最長級の連続増配銘柄です。" },
  { answer: "アサヒグループホールディングス", aliases: ["アサヒ", "アサヒビール"], ticker: "2502.T", code: "2502", sector: "ビール・飲料", mcap: "約3兆円", keyword: "スーパードライ・欧州ビール", kana: "あ", desc: "スーパードライで知られるビール最大手。欧州プレミアムビールが利益の柱です。" },
  { answer: "川崎重工業", aliases: ["川重"], ticker: "7012.T", code: "7012", sector: "重工", mcap: "約1.5兆円", keyword: "潜水艦・水素・Kawasaki", kana: "か", desc: "潜水艦や航空宇宙からバイクまで。防衛と水素が中長期テーマです。" },
  { answer: "IHI", aliases: ["石川島播磨", "ihi"], ticker: "7013.T", code: "7013", sector: "重工", mcap: "約2兆円", keyword: "航空エンジン・防衛", kana: "あ", desc: "航空エンジンと防衛が主力。民間航空の回復も追い風です。" },
  { answer: "ディスコ", aliases: ["disco"], ticker: "6146.T", code: "6146", sector: "半導体装置", mcap: "約5兆円", keyword: "ウエハ切削研磨で世界首位", kana: "で", desc: "ウエハ加工装置で世界シェア首位。AI半導体ブームの本命格です。" },
  // --- 31〜90 ---
  { answer: "ソフトバンクグループ", aliases: ["SBG", "softbank"], ticker: "9984.T", code: "9984", sector: "通信・投資", mcap: "約10兆円", keyword: "孫正義・Vision Fund・Arm", kana: "そ", desc: "孫正義氏が率いる投資持株会社。Arm上場やVision Fundの評価が焦点です。" },
  { answer: "三井物産", aliases: ["mitsui"], ticker: "8031.T", code: "8031", sector: "総合商社", mcap: "約8兆円", keyword: "五大商社・資源・インフラ", kana: "み", desc: "五大商社の一角。資源価格とインフラ投資が業績を左右します。" },
  { answer: "伊藤忠商事", aliases: ["itochu"], ticker: "8001.T", code: "8001", sector: "総合商社", mcap: "約12兆円", keyword: "ファミリーマート・非資源", kana: "い", desc: "非資源比率が高い総合商社。ファミマを傘下に持ち安定成長を目指します。" },
  { answer: "リクルートホールディングス", aliases: ["リクルート", "recruit"], ticker: "6098.T", code: "6098", sector: "人材・HR", mcap: "約12兆円", keyword: "Indeed・ホットペッパー", kana: "り", desc: "HRテック最大手。Indeedの成長と国内求人広告が収益の柱です。" },
  { answer: "信越化学工業", aliases: ["信越化学", "shin-etsu"], ticker: "4063.T", code: "4063", sector: "化学", mcap: "約8兆円", keyword: "シリコンウエハ世界首位", kana: "し", desc: "シリコンウエハで世界シェア首位。半導体材料の王者として知られます。" },
  { answer: "武田薬品工業", aliases: ["武田", "takeda"], ticker: "4502.T", code: "4502", sector: "医薬品", mcap: "約6兆円", keyword: "日本最大の製薬・シャイアー買収", kana: "た", desc: "売上高日本最大の製薬会社。シャイアー買収後の統合が焦点です。" },
  { answer: "セブン&アイ・ホールディングス", aliases: ["セブンイレブン", "7&i"], ticker: "3382.T", code: "3382", sector: "小売", mcap: "約5兆円", keyword: "セブンイレブン・非公開化", kana: "せ", desc: "セブンイレブンを展開する小売最大手。非公開化をめぐる動きが話題です。" },
  { answer: "イオン", aliases: ["aeon"], ticker: "8267.T", code: "8267", sector: "小売", mcap: "約3兆円", keyword: "GMS最大手・金融", kana: "い", desc: "総合スーパー最大手。GMS再編と金融事業が成長の柱です。" },
  { answer: "スズキ", aliases: ["suzuki"], ticker: "7269.T", code: "7269", sector: "自動車", mcap: "約3兆円", keyword: "インドシェア首位・軽自動車", kana: "す", desc: "インド市場で圧倒的シェア。軽自動車と新興国向けが強みです。" },
  { answer: "パナソニックホールディングス", aliases: ["パナソニック", "panasonic"], ticker: "6752.T", code: "6752", sector: "電機", mcap: "約4兆円", keyword: "車載電池・テスラ", kana: "ぱ", desc: "車載電池で世界大手。テスラ向け供給が長年の話題です。" },
  { answer: "LINEヤフー", aliases: ["LINE", "ヤフー", "ly corp"], ticker: "4689.T", code: "4689", sector: "IT・広告", mcap: "約4兆円", keyword: "LINE・PayPay・ZOZO親会社", kana: "ら", desc: "LINEとYahoo!を統合したIT大手。PayPayと広告が収益の柱です。" },
  { answer: "レーザーテック", aliases: ["lasertec"], ticker: "6920.T", code: "6920", sector: "半導体検査", mcap: "約2兆円", keyword: "EUVマスク検査で世界独占", kana: "れ", desc: "EUVマスク欠陥検査でほぼ独占。半導体微細化の必須装置メーカーです。" },
  { answer: "キリンホールディングス", aliases: ["キリン", "kirin"], ticker: "2503.T", code: "2503", sector: "ビール・飲料", mcap: "約1.5兆円", keyword: "一番搾り・ファンケル", kana: "き", desc: "ビールとヘルスサイエンス（ファンケル）を両輪にする飲料大手です。" },
  { answer: "明治ホールディングス", aliases: ["明治", "meiji"], ticker: "2269.T", code: "2269", sector: "食品", mcap: "約1兆円", keyword: "チョコレート・乳製品・医薬", kana: "め", desc: "チョコレートと乳製品の老舗。食品と医薬の両方を手がけます。" },
  { answer: "デンソー", aliases: ["denso"], ticker: "6902.T", code: "6902", sector: "自動車部品", mcap: "約5兆円", keyword: "トヨタ系・車載半導体", kana: "で", desc: "トヨタグループの部品最大手。EV化と車載半導体が成長テーマです。" },
  { answer: "村田製作所", aliases: ["murata"], ticker: "6981.T", code: "6981", sector: "電子部品", mcap: "約5兆円", keyword: "積層セラミックコンデンサ世界首位", kana: "む", desc: "電子部品の世界王者。スマホ向けMLCCで圧倒的シェアを持ちます。" },
  { answer: "ダイキン工業", aliases: ["ダイキン", "daikin"], ticker: "6367.T", code: "6367", sector: "空調", mcap: "約5兆円", keyword: "ルームエアコン世界首位", kana: "だ", desc: "ルームエアコン世界シェア首位。猛暑と脱炭素が追い風のグローバル企業です。" },
  { answer: "富士通", aliases: ["fujitsu"], ticker: "6702.T", code: "6702", sector: "IT", mcap: "約3兆円", keyword: "クラウド・5G・DX", kana: "ふ", desc: "国内IT最大手の一角。クラウドとDXサービスへの転換が進んでいます。" },
  { answer: "NEC", aliases: ["日本電気", "nec"], ticker: "6701.T", code: "6701", sector: "IT・通信", mcap: "約2兆円", keyword: "5G基地局・バイオ・AI", kana: "え", desc: "5G基地局とバイオ事業を柱に再建中。AI・量子も新領域です。" },
  { answer: "三菱電機", aliases: ["mitsubishi electric"], ticker: "6503.T", code: "6503", sector: "電機", mcap: "約4兆円", keyword: "エレベーター・FA・防衛", kana: "み", desc: "エレベーター世界大手。FA機器と防衛も手がける総合電機です。" },
  { answer: "SUBARU", aliases: ["スバル", "subaru"], ticker: "7270.T", code: "7270", sector: "自動車", mcap: "約2兆円", keyword: "水平対向エンジン・四輪駆動", kana: "す", desc: "水平対向エンジンとAWDが代名詞。北米向けが収益の柱です。" },
  { answer: "マツダ", aliases: ["mazda"], ticker: "7261.T", code: "7261", sector: "自動車", mcap: "約1兆円", keyword: "ロータリーエンジン・米国工場", kana: "ま", desc: "デザインと走りの自動車メーカー。米国工場の稼働率が焦点です。" },
  { answer: "コマツ", aliases: ["komatsu", "小松"], ticker: "6301.T", code: "6301", sector: "建設機械", mcap: "約4兆円", keyword: "油圧ショベル世界2位", kana: "こ", desc: "建設機械世界2位。資源価格とインフラ投資に連動する景気敏感株です。" },
  { answer: "ブリヂストン", aliases: ["bridgestone"], ticker: "5108.T", code: "5108", sector: "タイヤ", mcap: "約4兆円", keyword: "タイヤ世界最大手", kana: "ぶ", desc: "タイヤ世界最大手。原材料価格と為替が利益率を左右します。" },
  { answer: "味の素", aliases: ["ajinomoto"], ticker: "2802.T", code: "2802", sector: "食品", mcap: "約2兆円", keyword: "うま味調味料・アミノ酸", kana: "あ", desc: "うま味調味料で知られる食品大手。アミノサイエンスが新たな柱です。" },
  { answer: "キッコーマン", aliases: ["kikkoman"], ticker: "2801.T", code: "2801", sector: "食品", mcap: "約1.5兆円", keyword: "しょうゆ世界シェア", kana: "き", desc: "しょうゆで世界シェア首位。海外売上比率が高い日本食の代表企業です。" },
  { answer: "日本たばこ産業", aliases: ["JT", "jti"], ticker: "2914.T", code: "2914", sector: "たばこ", mcap: "約8兆円", keyword: "加熱式たばこ・海外M&A", kana: "に", desc: "国内たばこ最大手。加熱式たばこと海外事業が成長の柱です。" },
  { answer: "中外製薬", aliases: ["chugai"], ticker: "4519.T", code: "4519", sector: "医薬品", mcap: "約12兆円", keyword: "ロシュグループ・抗体医薬", kana: "ち", desc: "ロシュグループ傘下。抗体医薬のパイプラインが評価の中心です。" },
  { answer: "テルモ", aliases: ["terumo"], ticker: "4543.T", code: "4543", sector: "医療機器", mcap: "約3兆円", keyword: "カテーテル・人工心肺", kana: "て", desc: "カテーテル等の医療機器大手。高齢化社会の恩恵を受けるディフェンシブ株です。" },
  { answer: "大塚ホールディングス", aliases: ["大塚製薬", "otsuka"], ticker: "4578.T", code: "4578", sector: "医薬品・飲料", mcap: "約2兆円", keyword: "ポカリスエット・输液", kana: "お", desc: "ポカリスエットで知られる。医薬と機能性飲料の両方を手がけます。" },
  { answer: "エーザイ", aliases: ["eisai"], ticker: "4523.T", code: "4523", sector: "医薬品", mcap: "約1.5兆円", keyword: "レケンビ・アルツハイマー", kana: "え", desc: "アルツハイマー治療薬レケンビで話題。Biogenとの提携が焦点でした。" },
  { answer: "アステラス製薬", aliases: ["astellas"], ticker: "4503.T", code: "4503", sector: "医薬品", mcap: "約2兆円", keyword: "創薬・XTANDI", kana: "あ", desc: "前立腺がん治療薬XTANDI等の創薬大手。パイプライン刷新が課題です。" },
  { answer: "野村ホールディングス", aliases: ["野村", "nomura"], ticker: "8604.T", code: "8604", sector: "証券", mcap: "約1.5兆円", keyword: "日本最大の証券・投資銀行", kana: "の", desc: "日本最大の証券会社。株式相場と投資銀行部門の稼ぎが業績を左右します。" },
  { answer: "三井住友フィナンシャルグループ", aliases: ["三井住友FG", "SMFG"], ticker: "8316.T", code: "8316", sector: "銀行", mcap: "約15兆円", keyword: "メガバンク・海外展開", kana: "み", desc: "メガバンク第2位。金利上昇と海外事業が収益の柱です。" },
  { answer: "みずほフィナンシャルグループ", aliases: ["みずほFG", "mizuho"], ticker: "8411.T", code: "8411", sector: "銀行", mcap: "約10兆円", keyword: "メガバンク・システム障害", kana: "み", desc: "メガバンク第3位。利上げ恩恵とIT投資が株価のテーマです。" },
  { answer: "オリックス", aliases: ["orix"], ticker: "8591.T", code: "8591", sector: "リース・金融", mcap: "約3兆円", keyword: "リース最大手・再生エネ", kana: "お", desc: "リース・金融の総合企業。再生エネや不動産も手がける多角化企業です。" },
  { answer: "住友商事", aliases: ["sumitomo"], ticker: "8053.T", code: "8053", sector: "総合商社", mcap: "約5兆円", keyword: "五大商社・金属・メディア", kana: "す", desc: "五大商社の一角。金属事業とメディア（St. Regis）が特色です。" },
  { answer: "丸紅", aliases: ["marubeni"], ticker: "8002.T", code: "8002", sector: "総合商社", mcap: "約4兆円", keyword: "五大商社・穀物・電力", kana: "ま", desc: "穀物取扱量世界最大級。電力・インフラも手がける総合商社です。" },
  { answer: "INPEX", aliases: ["インペックス", "inpex"], ticker: "1605.T", code: "1605", sector: "石油開発", mcap: "約2兆円", keyword: "石油天然ガス開発・イクシス", kana: "い", desc: "石油・ガス開発の国家系企業。原油価格とイクシスLNGが業績の柱です。" },
  { answer: "東京ガス", aliases: ["tokyo gas"], ticker: "9531.T", code: "9531", sector: "ガス", mcap: "約1.5兆円", keyword: "都市ガス首都圏・脱炭素", kana: "と", desc: "首都圏の都市ガス最大手。脱炭素・水素事業への転換が進んでいます。" },
  { answer: "JFEホールディングス", aliases: ["JFE", "jfe"], ticker: "5411.T", code: "5411", sector: "鉄鋼", mcap: "約1兆円", keyword: "高炉・造船・エンジニアリング", kana: "じ", desc: "日本製鉄に次ぐ鉄鋼大手。造船・エンジニアリングも手がけます。" },
  { answer: "TDK", aliases: ["tdk"], ticker: "6762.T", code: "6762", sector: "電子部品", mcap: "約2兆円", keyword: "電池・センサー・HDD部品", kana: "て", desc: "電池・センサー等の電子部品大手。EV向け電池が成長テーマです。" },
  { answer: "キャノン", aliases: ["canon"], ticker: "7751.T", code: "7751", sector: "精密機器", mcap: "約4兆円", keyword: "カメラ・プリンター・半導体露光", kana: "き", desc: "カメラとプリンターで知られる。半導体露光装置も手がけます。" },
  { answer: "リコー", aliases: ["ricoh"], ticker: "7752.T", code: "7752", sector: "OA機器", mcap: "約6000億円", keyword: "複合機・THETA・印刷", kana: "り", desc: "OA複合機大手。オフィスDXと商用印刷が収益の柱です。" },
  { answer: "AGC", aliases: ["旭硝子", "agc"], ticker: "5201.T", code: "5201", sector: "ガラス", mcap: "約8000億円", keyword: "ガラス・ディスプレイ・化学", kana: "え", desc: "ガラス最大手。ディスプレイ用ガラスと化学事業も展開しています。" },
  { answer: "カプコン", aliases: ["capcom"], ticker: "9697.T", code: "9697", sector: "ゲーム", mcap: "約2兆円", keyword: "モンスターハンター・バイオ", kana: "か", desc: "モンハン・バイオハザード等のヒット作を持つゲームメーカーです。" },
  { answer: "スクウェア・エニックス", aliases: ["スクエニ", "square enix"], ticker: "9684.T", code: "9684", sector: "ゲーム", mcap: "約8000億円", keyword: "FF・ドラクエ", kana: "す", desc: "FF・ドラクエを擁するRPGの名門。新作の売上が株価を大きく動かします。" },
  { answer: "バンダイナムコホールディングス", aliases: ["バンナム", "bandai namco"], ticker: "7832.T", code: "7832", sector: "ゲーム・玩具", mcap: "約3兆円", keyword: "ガンプラ・鉄拳・IP", kana: "ば", desc: "ガンプラとゲームIPが強み。アミューズメントも手がけるエンタメ企業です。" },
  { answer: "セコム", aliases: ["secom"], ticker: "9735.T", code: "9735", sector: "セキュリティ", mcap: "約2兆円", keyword: "警備最大手・ホームセキュリティ", kana: "せ", desc: "警備サービス最大手。ホームセキュリティとBPOも成長分野です。" },
  { answer: "ヤマトホールディングス", aliases: ["ヤマト運輸", "クロネコ"], ticker: "9064.T", code: "9064", sector: "物流", mcap: "約6000億円", keyword: "宅配最大手・クロネコ", kana: "や", desc: "宅配便最大手。人手不足と運賃改定が業界全体の課題です。" },
  { answer: "日本郵船", aliases: ["NYK", "nyk line"], ticker: "9101.T", code: "9101", sector: "海運", mcap: "約1.5兆円", keyword: "海運最大手・LNG運搬", kana: "に", desc: "日本最大の海運会社。運賃指数（BDI）に連動する景気敏感株です。" },
  { answer: "三菱ケミカルグループ", aliases: ["三菱ケミカル"], ticker: "4188.T", code: "4188", sector: "化学", mcap: "約1兆円", keyword: "石化・機能材料・医薬", kana: "み", desc: "石化から機能材料まで手がける化学大手。半導体材料も成長分野です。" },
  { answer: "旭化成", aliases: ["asahi kasei"], ticker: "3407.T", code: "3407", sector: "化学", mcap: "約1.5兆円", keyword: "ヘルスケア・電池材料", kana: "あ", desc: "ヘルスケアと電池材料（セパレーター）が成長の柱です。" },
  { answer: "シスメックス", aliases: ["sysmex"], ticker: "6869.T", code: "6869", sector: "医療機器", mcap: "約2兆円", keyword: "血液検査装置世界首位", kana: "し", desc: "血液検査装置で世界シェア首位。高齢化で安定成長が期待されます。" },
  { answer: "HOYA", aliases: ["ホーヤ", "hoya"], ticker: "7741.T", code: "7741", sector: "精密機器", mcap: "約5兆円", keyword: "メガネレンズ・半導体マスク", kana: "ほ", desc: "メガネレンズと半導体マスクの二刀流。高い利益率が魅力です。" },
  { answer: "オムロン", aliases: ["omron"], ticker: "6645.T", code: "6645", sector: "FA・ヘルスケア", mcap: "約8000億円", keyword: "血圧計・FA制御", kana: "お", desc: "血圧計とFA制御機器の大手。ヘルスケアと産業自動化の両輪です。" },
  { answer: "ニデック", aliases: ["nidec", "日本電産"], ticker: "6594.T", code: "6594", sector: "モーター", mcap: "約3兆円", keyword: "小型モーター世界首位", kana: "に", desc: "小型モーター世界シェア首位。EV向けe-Axleが次の成長柱です。" },
  { answer: "ファナック", aliases: ["fanuc"], ticker: "6954.T", code: "6954", sector: "FA・ロボット", mcap: "約4兆円", keyword: "工作機械CNC・産業ロボット", kana: "ふ", desc: "CNCと産業ロボットの世界王者。中国の設備投資に連動しやすい銘柄です。" },
  { answer: "アドバンテスト", aliases: ["advantest"], ticker: "6857.T", code: "6857", sector: "半導体テスト", mcap: "約6兆円", keyword: "半導体テスト装置世界首位", kana: "あ", desc: "半導体テスト装置の世界首位。AI半導体需要で業績が急拡大しました。" },
  { answer: "MS&ADインシュアランスグループホールディングス", aliases: ["MS&AD", "msad"], ticker: "8725.T", code: "8725", sector: "損害保険", mcap: "約5兆円", keyword: "損保最大手・三井住友海上", kana: "え", desc: "国内最大の損害保険グループ。自然災害の激甚化が業績に影響します。" },
  { answer: "JR東日本", aliases: ["JR東", "jreast"], ticker: "9020.T", code: "9020", sector: "鉄道", mcap: "約3兆円", keyword: "首都圏鉄道・不動産・駅ナカ", kana: "じ", desc: "首都圏の鉄道最大手。不動産と駅ナカ事業も収益の柱です。" },
  { answer: "西日本旅客鉄道", aliases: ["JR西日本", "jrw"], ticker: "9021.T", code: "9021", sector: "鉄道", mcap: "約1.5兆円", keyword: "関西圏鉄道・インバウンド", kana: "に", desc: "関西圏の鉄道会社。インバウンド回復が業績の追い風です。" },
  { answer: "オリンパス", aliases: ["olympus"], ticker: "7733.T", code: "7733", sector: "医療機器", mcap: "約4000億円", keyword: "内視鏡世界シェア首位", kana: "お", desc: "内視鏡で世界シェア首位。スキャンダル後の再建が進んでいます。" },
  { answer: "コナミグループ", aliases: ["コナミ", "konami"], ticker: "9766.T", code: "9766", sector: "ゲーム", mcap: "約1.5兆円", keyword: "eFootball・パチンコ・スポーツ", kana: "こ", desc: "ゲーム・スポーツクラブ・フィットネスを手がけるエンタメ企業です。" },
  { answer: "サンリオ", aliases: ["sanrio", "ハローキティ"], ticker: "8136.T", code: "8136", sector: "キャラクター", mcap: "約6000億円", keyword: "ハローキティ・キャラクターIP", kana: "さ", desc: "ハローキティで知られるキャラクターIP企業。ライセンス収入が柱です。" },
  { answer: "トレンドマイクロ", aliases: ["trend micro"], ticker: "4704.T", code: "4704", sector: "セキュリティソフト", mcap: "約1.5兆円", keyword: "サイバーセキュリティ・ウイルス対策", kana: "と", desc: "ウイルス対策ソフト最大手。サイバー攻撃増加が追い風です。" },
  { answer: "マネーフォワード", aliases: ["moneyforward"], ticker: "3994.T", code: "3994", sector: "SaaS", mcap: "約3000億円", keyword: "クラウド会計・バックオフィス", kana: "ま", desc: "クラウド会計最大手。バックオフィスSaaSの代表格です。" },
  { answer: "freee", aliases: ["フリー"], ticker: "4478.T", code: "4478", sector: "SaaS", mcap: "約2000億円", keyword: "クラウド会計・中小向け", kana: "ふ", desc: "中小企業向けクラウド会計。マネーフォワードと双璧をなすSaaS企業です。" },
  { answer: "ソフトバンク", aliases: ["softbank corp"], ticker: "9434.T", code: "9434", sector: "通信", mcap: "約10兆円", keyword: "Y!mobile・PayPay・孫正義", kana: "そ", desc: "SBGとは別の通信子会社。PayPayとモバイルが主力事業です。" },
  { answer: "ヤマハ発動機", aliases: ["ヤマハ", "yamaha"], ticker: "7272.T", code: "7272", sector: "二輪・マリン", mcap: "約1.5兆円", keyword: "バイク・ボート・ピアノ", kana: "や", desc: "バイク世界大手。マリン（ボート）とピアノも手がける多角化企業です。" },
  { answer: "クボタ", aliases: ["kubota"], ticker: "6326.T", code: "6326", sector: "農機", mcap: "約2兆円", keyword: "トラクター・用水路・北米", kana: "く", desc: "トラクター世界大手。北米農業機械とインフラ（用水路）が強みです。" },
  { answer: "積水化学工業", aliases: ["積水化学", "sekisui"], ticker: "4204.T", code: "4204", sector: "化学・建材", mcap: "約1.5兆円", keyword: "ハウス・パイプ・ディスプレイ", kana: "せ", desc: "ハウスメーカーと化学の二刀流。住宅と高機能プラスチックが柱です。" },
  { answer: "LIXIL", aliases: ["リクシル", "lixil"], ticker: "5938.T", code: "5938", sector: "建材", mcap: "約5000億円", keyword: "トイレ・水栓・建材", kana: "り", desc: "トイレ・水栓金具世界大手。米国住宅市場にも展開しています。" },
  { answer: "日本航空", aliases: ["JAL", "jal"], ticker: "9201.T", code: "9201", sector: "空運", mcap: "約1.2兆円", keyword: "国際線・インバウンド・LCC", kana: "に", desc: "ANAと双璧の航空会社。国際線とLCC（Jetstar）が収益の柱です。" },
  { answer: "東急", aliases: ["tokyu"], ticker: "9005.T", code: "9005", sector: "鉄道・不動産", mcap: "約1兆円", keyword: "渋谷再開発・私鉄", kana: "と", desc: "渋谷再開発を推進する私鉄。鉄道と不動産の両輪で稼ぐ企業です。" },
  { answer: "三菱ガス化学", aliases: ["MGC", "mgc"], ticker: "4182.T", code: "4182", sector: "化学", mcap: "約6000億円", keyword: "メタノール・エンジニアリングプラスチック", kana: "み", desc: "メタノールと機能性樹脂が強み。半導体向け材料も成長分野です。" },
];
